"use client";

import { motion } from "framer-motion";
import { GlassCard } from "@/components/ui/GlassCard";
import { SectionWrapper } from "@/components/ui/SectionWrapper";
import { useEve } from "@/contexts/EveContext";
import { useRef } from "react";

export function HeroSection() {
    const { setInteraction, clearInteraction } = useEve();
    const terminalRef = useRef<HTMLDivElement>(null);

    const codeString = `
<span class="text-pink-400">from</span> Autodesk.Revit.DB <span class="text-pink-400">import</span> *

<span class="text-zinc-500"># Generated by Plotina</span>
collector = FilteredElementCollector(doc)
doors = collector.OfCategory(BuiltInCategory.OST_Doors)\\
                 .WhereElementIsNotElementType()\\
                 .ToElements()

unmarked_count = <span class="text-orange-300">0</span>
<span class="text-pink-400">for</span> door <span class="text-pink-400">in</span> doors:
    level = doc.GetElement(door.LevelId)
    <span class="text-pink-400">if</span> level <span class="text-pink-400">and</span> level.Name == <span class="text-emerald-300">"Level 1"</span>:
        mark = door.get_Parameter(BuiltInParameter.ALL_MODEL_MARK).AsString()
        <span class="text-pink-400">if not</span> mark:
            unmarked_count += <span class="text-orange-300">1</span>

<span class="text-cyan-300">print</span>(<span class="text-emerald-300">f"Found {unmarked_count} doors without marks on Level 1"</span>)
`.trim();

    return (
        <SectionWrapper className="relative pt-24 pb-16 flex flex-col justify-center min-h-[90vh] overflow-hidden">
            {/* Animated SVG Background */}
            <div className="absolute inset-0 z-0 pointer-events-none opacity-30">
                <svg className="w-full h-full" xmlns="http://www.w3.org/2000/svg">
                    <defs>
                        <linearGradient id="glowGradient" x1="0%" y1="0%" x2="100%" y2="100%">
                            <stop offset="0%" stopColor="#10b981" stopOpacity="0.2" />
                            <stop offset="100%" stopColor="#059669" stopOpacity="0" />
                        </linearGradient>
                    </defs>
                    <motion.circle
                        cx="20%" cy="30%" r="150" fill="url(#glowGradient)"
                        animate={{ r: [150, 180, 150], opacity: [0.5, 0.8, 0.5] }}
                        transition={{ duration: 8, repeat: Infinity, ease: "easeInOut" }}
                    />
                    <motion.circle
                        cx="80%" cy="70%" r="200" fill="url(#glowGradient)"
                        animate={{ r: [200, 230, 200], opacity: [0.3, 0.6, 0.3], cx: ["80%", "78%", "80%"] }}
                        transition={{ duration: 10, repeat: Infinity, ease: "easeInOut" }}
                    />
                    {/* Floating nodes and connections */}
                    <g stroke="#ffffff" strokeOpacity="0.05" strokeWidth="1">
                        <motion.line x1="20%" y1="30%" x2="40%" y2="60%"
                            animate={{ strokeOpacity: [0.05, 0.15, 0.05] }}
                            transition={{ duration: 4, repeat: Infinity, ease: "easeInOut" }} />
                        <motion.line x1="40%" y1="60%" x2="80%" y2="70%"
                            animate={{ strokeOpacity: [0.05, 0.2, 0.05] }}
                            transition={{ duration: 5, repeat: Infinity, ease: "easeInOut", delay: 1 }} />
                        <motion.line x1="80%" y1="70%" x2="60%" y2="20%"
                            animate={{ strokeOpacity: [0.05, 0.15, 0.05] }}
                            transition={{ duration: 6, repeat: Infinity, ease: "easeInOut", delay: 2 }} />
                        <motion.line x1="60%" y1="20%" x2="20%" y2="30%"
                            animate={{ strokeOpacity: [0.05, 0.2, 0.05] }}
                            transition={{ duration: 5.5, repeat: Infinity, ease: "easeInOut", delay: 0.5 }} />
                    </g>
                    <g fill="#ffffff" fillOpacity="0.1">
                        <circle cx="40%" cy="60%" r="3" />
                        <circle cx="60%" cy="20%" r="4" />
                        <circle cx="20%" cy="30%" r="5" />
                        <circle cx="80%" cy="70%" r="3" />
                    </g>
                </svg>
            </div>

            <div className="relative z-10 text-center max-w-4xl mx-auto mb-16 space-y-6">
                <motion.div
                    initial={{ opacity: 0, scale: 0.9 }}
                    animate={{ opacity: 1, scale: 1 }}
                    transition={{ duration: 0.8, ease: "easeOut" }}
                    className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 text-sm font-medium mb-4 backdrop-blur-md"
                >
                    <span className="relative flex h-2 w-2">
                        <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
                        <span className="relative inline-flex rounded-full h-2 w-2 bg-emerald-500"></span>
                    </span>
                    Plotina 1.0 is now live
                </motion.div>
                <motion.h1
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.8, ease: "easeOut" }}
                    className="text-5xl md:text-7xl font-bold tracking-tight text-white"
                >
                    Talk to Revit. Let <span className="text-gradient from-emerald-400 to-emerald-600 bg-gradient-to-r">Plotina</span> write the code.
                </motion.h1>
                <motion.p
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.8, delay: 0.2, ease: "easeOut" }}
                    className="text-xl md:text-2xl text-zinc-400 font-medium max-w-2xl mx-auto"
                >
                    The infrastructure layer for BIM automation. Turn natural language into executable IronPython instantly.
                </motion.p>

                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.8, delay: 0.4, ease: "easeOut" }}
                    className="flex flex-col sm:flex-row items-center justify-center gap-4 pt-6"
                >
                    <button className="w-full sm:w-auto bg-emerald-500 hover:bg-emerald-400 text-zinc-950 px-8 py-3.5 rounded-full font-semibold transition-all duration-300 primary-glow hover:scale-105">
                        Start Automating
                    </button>
                    <button className="w-full sm:w-auto bg-transparent border border-white/20 hover:border-white/40 hover:bg-white/5 text-white px-8 py-3.5 rounded-full font-medium transition-all duration-300 backdrop-blur-sm">
                        Read the Docs
                    </button>
                </motion.div>
            </div>

            <motion.div
                initial={{ opacity: 0, y: 40 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 1, delay: 0.6, ease: "easeOut" }}
                className="relative z-10 grid grid-cols-1 lg:grid-cols-2 gap-8 items-center max-w-6xl mx-auto w-full"
            >
                <div className="relative group">
                    <div className="absolute -inset-1 bg-gradient-to-r from-emerald-500/20 to-zinc-500/20 rounded-2xl blur opacity-25 group-hover:opacity-50 transition duration-1000 group-hover:duration-200" />
                    <GlassCard className="p-8 relative">
                        <div className="flex gap-4 items-start">
                            <div className="w-10 h-10 rounded-full bg-zinc-800 flex items-center justify-center shrink-0 border border-white/10 shadow-inner">
                                <span className="text-sm font-semibold text-zinc-300">U</span>
                            </div>
                            <div className="bg-white/5 backdrop-blur-md p-4 rounded-2xl rounded-tl-sm text-zinc-200 shadow-sm border border-white/10 relative overflow-hidden">
                                <motion.div
                                    className="absolute inset-0 bg-gradient-to-r from-transparent via-white/5 to-transparent -translate-x-full"
                                    animate={{ translateX: ["-100%", "200%"] }}
                                    transition={{ duration: 2, ease: "easeInOut", repeat: Infinity, repeatDelay: 3 }}
                                />
                                "Count all doors without a mark on level 1."
                            </div>
                        </div>
                    </GlassCard>
                </div>

                <div
                    className="relative group cursor-none"
                    onMouseEnter={() => setInteraction({
                        type: 'explaining',
                        thoughtText: "I translate your words into IronPython instantly.",
                        targetRef: terminalRef
                    })}
                    onMouseLeave={clearInteraction}
                    ref={terminalRef}
                >
                    <div className="absolute -inset-1 bg-gradient-to-r from-emerald-500/20 to-zinc-500/20 rounded-2xl blur opacity-25 group-hover:opacity-50 transition duration-1000 group-hover:duration-200" />
                    <GlassCard className="p-0 overflow-hidden border-zinc-800/50 bg-[#1e1e1e]/90 backdrop-blur-xl relative">
                        <div className="bg-[#2d2d2d]/80 backdrop-blur-md px-4 py-3 flex items-center border-b border-black/20">
                            <div className="flex gap-2">
                                <div className="w-3 h-3 rounded-full bg-red-500/80 shadow-[0_0_5px_rgba(239,68,68,0.5)]"></div>
                                <div className="w-3 h-3 rounded-full bg-yellow-500/80 shadow-[0_0_5px_rgba(234,179,8,0.5)]"></div>
                                <div className="w-3 h-3 rounded-full bg-green-500/80 shadow-[0_0_5px_rgba(34,197,94,0.5)]"></div>
                            </div>
                            <span className="text-xs text-zinc-400 ml-4 font-mono">script.py</span>
                        </div>
                        <div className="p-6 font-mono text-sm text-zinc-300 h-[300px] overflow-hidden relative">
                            <motion.pre
                                initial={{ opacity: 0 }}
                                animate={{ opacity: 1 }}
                                transition={{ duration: 0.5, delay: 1.2 }}
                            >
                                <motion.code
                                    className="block relative z-10"
                                    initial={{ clipPath: "polygon(0 0, 10% 0, 10% 100%, 0 100%)" }}
                                    animate={{ clipPath: "polygon(0 0, 100% 0, 100% 100%, 0 100%)" }}
                                    transition={{ duration: 3, delay: 1.5, ease: "linear" }}
                                    dangerouslySetInnerHTML={{ __html: codeString }}
                                />
                            </motion.pre>
                            {/* Blinking cursor */}
                            <motion.div
                                className="w-2 h-4 bg-emerald-400 absolute mt-1 inline-block"
                                animate={{ opacity: [1, 0] }}
                                transition={{ duration: 0.8, repeat: Infinity, repeatType: "reverse" }}
                                style={{ top: "1.5rem", left: "1.5rem" }}
                            />
                        </div>
                    </GlassCard>
                </div>
            </motion.div>
        </SectionWrapper>
    );
}
